name: ros-metrics
channels:
  - conda-forge
dependencies:
  - python==3.11.4
  - numpy==1.25.1
  - pandas==2.0.3
  - scipy==1.11.1
  - xarray==2023.7.0
  - matplotlib==3.7.2
  - jpeg==9e
  - metpy==1.5.*
  - netcdf4>=1.6
  - imagemagick=7.1
  - parallel=20240522
  - ncl